# Generated by Django 4.2.6 on 2023-11-07 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default=True, max_length=1000)),
                ('request_friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recevie_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
