# Generated by Django 4.2.6 on 2023-11-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_addfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfriends',
            name='receive_friends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addfriends',
            name='request_friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
